# Generated by Django 4.0.3 on 2022-04-15 09:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftData',
            fields=[
                ('aircraft_code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('model', models.JSONField()),
                ('range', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'db_table': 'aircrafts_data',
            },
        ),
        migrations.CreateModel(
            name='AirportData',
            fields=[
                ('airport_code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('airport_name', models.JSONField()),
                ('city', models.JSONField()),
                ('coordinates', models.CharField(max_length=30)),
                ('timezone', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'airports_data',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('book_ref', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('book_date', models.DateTimeField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='TicketFlight',
            fields=[
                ('ticket_no', models.CharField(max_length=13, primary_key=True)),
                ('flight_id', models.IntegerField()),
                ('fare_conditions', models.CharField(choices=[('Economy', 'Economy'), ('Comfort', 'Comfort'), ('Business', 'Business')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'ticket_flights',
                'unique_together': {('ticket_no', 'flight_id')},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_no', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('passenger_id', models.CharField(max_length=20)),
                ('passenger_name', models.TextField()),
                ('contact_data', models.JSONField()),
                ('book_ref', models.ForeignKey(db_column='book_ref', on_delete=django.db.models.fields.NOT_PROVIDED, to='bookings.booking')),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('flight_no', models.CharField(max_length=6)),
                ('scheduled_departure', models.DateTimeField()),
                ('scheduled_arrival', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('actual_departure', models.DateTimeField()),
                ('actual_arrival', models.DateTimeField()),
                ('aircraft_code', models.ForeignKey(db_column='aircraft_code', on_delete=django.db.models.fields.NOT_PROVIDED, to='bookings.aircraftdata')),
                ('arrival_airport', models.ForeignKey(db_column='arrival_airport', on_delete=django.db.models.fields.NOT_PROVIDED, related_name='arrival_airport', to='bookings.airportdata')),
                ('departure_airport', models.ForeignKey(db_column='departure_airport', on_delete=django.db.models.fields.NOT_PROVIDED, related_name='departure_airport', to='bookings.airportdata')),
            ],
            options={
                'db_table': 'flights',
            },
        ),
        migrations.CreateModel(
            name='BoardingPass',
            fields=[
                ('ticket_no', models.CharField(max_length=13, primary_key=True)),
                ('flight_id', models.IntegerField()),
                ('boarding_no', models.IntegerField()),
                ('seat_no', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'boarding_passes',
                'unique_together': {('ticket_no', 'flight_id')},
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seat_no', models.CharField(max_length=4, primary_key=True)),
                ('fare_conditions', models.CharField(choices=[('Economy', 'Economy'), ('Comfort', 'Comfort'), ('Business', 'Business')], max_length=20)),
                ('aircraft_code', models.ForeignKey(db_column='aircraft_code', on_delete=django.db.models.deletion.CASCADE, to='bookings.aircraftdata')),
            ],
            options={
                'db_table': 'seats',
                'unique_together': {('aircraft_code', 'seat_no')},
            },
        ),
    ]
