# Generated by Django 4.0.3 on 2022-04-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircrafts_Data',
            fields=[
                ('aircraft_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('model', models.JSONField()),
                ('range', models.IntegerField()),
            ],
        ),
    ]
