# Generated by Django 4.0.4 on 2022-04-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boardingpass',
            unique_together={('ticket_no', 'flight_id')},
        ),
        migrations.AlterField(
            model_name='airportdata',
            name='coordinates',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='boardingpass',
            name='ticket_no',
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('On Time', 'On Time'), ('Delayed', 'Delayed'), ('Departed', 'Departed'), ('Arrived', 'Arrived'), ('Scheduled', 'Scheduled'), ('Cancelled', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_no',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticketflight',
            name='ticket_no',
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='boardingpass',
            unique_together={('ticket_no', 'flight_id'), ('flight_id', 'boarding_no'), ('flight_id', 'seat_no')},
        ),
        migrations.AlterUniqueTogether(
            name='flight',
            unique_together={('flight_no', 'scheduled_departure')},
        ),
    ]
